name: Build and release
on:
  push:
    branches:
      - main

env:
  image_name: ghcr.io/giganticminecraft/seichiassist-downloader

jobs:
  build-image:
    name: Build server docker image
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.meta.outputs.tags }}
    concurrency:
      group: ${{ github.ref }}-docker-build
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.image_name }}
          tags: |
            type=sha,prefix=sha-,suffix=,format=short

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./server
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          # すべてのビルドステージのすべてのレイヤーをキャッシュして欲しいのでmode=max
          cache-to: type=gha,mode=max
